version: '3'

networks:
  mynetwork:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/bjin/data/wordpress #리눅스 환경에서는 변경 필요
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/bjin/data/mariadb #리눅스 환경에서는 변경 필요
      o: bind

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - mynetwork

  wordpress:
    build: ./requirements/wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_DB_HOST: mariadb
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${MYSQL_DATABASE}
      WP_TITLE: ${WP_TITLE}
      WP_THEME: ${WP_THEME}
      WP_PLUGINS: ${WP_PLUGINS}

      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}

      ADMIN_USER: ${WP_ADMIN_USER}
      ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

      EXTRA_USER: ${EXTRA_USER}
      EXTRA_USER_EMAIL: ${EXTRA_USER_EMAIL}
      EXTRA_USER_PASSWORD: ${EXTRA_USER_PASSWORD}
      EXTRA_USER_ROLE: ${EXTRA_USER_ROLE}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - mynetwork

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
